# 将静态内容部署到 GitHub Pages 的简单工作流程
名称：将静态内容部署到页面

在：
  # 针对默认分支的个体上运动
  推：
    修改：[ “主要” ]

  # 允许您从“操作”选项卡手动运行此工作流程
  活动调度：

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
权限：
  内容：已读
  页数：写
  id-token : 写入

# 只允许一次并发部署，跳过正在进行的运行和最新排队之间的排队运行。
#但是完成后，不要取消发射的运行，因为我们希望这些生产部署能够。
并发性：
  组：“页面”
  取消进行中：false

工作：
  # 由于我们只是部署，因此采用单一部署作业
  部署：
    环境：
      名称： github-pages
      网址： $ {  { steps.deployment.outputs.page_url }  }
    运行于： ubuntu-latest
    脚步：
      -名称：结帐
        用途：actions/checkout@v4
      -名称：设置页面
        用途： actions/configure-pages@v5
      -名称：上传工件
        用途： actions/upload-pages-artifact@v3
        和：
          # 上传整个仓库
          小路：'。'
      -名称：到配置GitHub Pages
        id：部署
        用途： actions/deploy-pages@v4
